import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Game } from "../components/Game";
import { Letter } from "../components/Letter";
import { Word } from "../components/Word";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [revealed, setRevealed] = useState<string[]>(["l"]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Game />
      </main>
    </div>
  );
};

export default Home;
